# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# format = """
# [](#DA627D)(bg:#DA627D fg:#9A348E)\
# $directory\
# [](fg:#DA627D bg:#FCA17D)\
# $git_branch\
# $git_status\
# [](fg:#FCA17D bg:#86BBD8)\
# [](fg:#86BBD8 bg:#33658A)\
# $docker_context\
# [ ](fg:#33658A)\
# """
format = """
(fg:#DDFF1F bg:#1FC0FF)\
$directory\
[](fg:#1FC0FF bg:#DDFF1F)\
${env_var.WINGETUPDATESCOUNT}\
[](fg:#DDFF1F bg:#FF1FBF)\
$git_branch\
$git_status\
[](fg:#FF1FBF bg:#FF5B1F)\
$docker_context\
[ ](fg:#FF5B1F)\
"""

# \n  >_ \
# ${custom.wingetupdates}\
#$c\
#$elixir\
#$elm\
#$golang\
#$haskell\
#$java\
#$julia\
#$nodejs\
#$nim\
#$rust\
#$scala\
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = false
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = false # Disabled by default

[directory]
style = "bg:#1FC0FF fg:#000000"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[python]
symbol = " "
pyenv_version_name = true
format = 'via [${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bg:#FF1FBF"
pyenv_prefix = "venv "
#python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#FF1FBF"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FF1FBF"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#FF1FBF"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ $time ]($style)'

# [custom.wingetupdates]
# # command = ". $HOME/Documents/Powershell/profile/function.ps1 $count = Get-WinGetUpdates; $count.Count"
# # command = ". C:\\Users\\will\\Documents\\PowerShell\\profile\\functions.ps1 && Get-WinGetUpdatesCount"
# command = ". $HOME\\Documents\\PowerShell\\profile\\functions.ps1 && Get-WinGetUpdatesCount"
# description = "Number of outdated winget packages"
# symbol = " "
# when = true
# style = "bg:#DDFF1F fg:#000000"
# format = "[ $symbol($output) ]($style)"
# shell = ['pwsh.exe', '-NoProfile', '-Command' , '-']
# ignore_timeout = true

[custom.wingetupdates]

command = ". $HOME\\Documents\\PowerShell\\profile\\functions.ps1 && Get-WinGetUpdatesCount"
description = "Number of outdated winget packages"
symbol = " "
when = true
style = "bg:#DDFF1F fg:#000000"
format = "[ $symbol($output) ]($style)"
shell = ['pwsh.exe', '-NoProfile', '-Command' , '-']
ignore_timeout = true

[env_var.WINGETUPDATESCOUNT]
style = "bg:#DDFF1F fg:#000000"
symbol = " "
variable = 'WINGETUPDATESCOUNT'
default = '--'
format = "[ $symbol($env_value) ]($style)"
disabled = false